## 透過機器學習預測「電信業」顧客流失率 -揭秘機器學習建模與不平衡資料集處理實戰
### 作者：張家穎(臺灣行銷研究特邀作者)、徐佳靖(臺灣行銷研究特邀作者)、林蔚恩(臺灣行銷研究特邀作者)
### 原始資料請見[本連結](https://www.kaggle.com/blastchar/telco-customer-churn)，並請參考[系列文1](https://medium.com/@chiayinchang/bde4b3fbad52)，下載下來後將pd.read_csv()內的路徑改為資料集的路徑即可

In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import seaborn as sns # For creating plots
import matplotlib.ticker as mtick # For specifying the axes tick format 
import matplotlib.pyplot as plt
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import seaborn as sns # For creating plots
import matplotlib.ticker as mtick # For specifying the axes tick format 
import matplotlib.pyplot as plt
import sklearn
import scipy
from sklearn.model_selection import train_test_split
from collections import Counter

In [2]:
telecom_cust = pd.read_csv('WA_Fn-UseC_-Telco-Customer-Churn.csv')

In [3]:
telecom_cust.sample

<bound method NDFrame.sample of       customerID  gender  SeniorCitizen Partner Dependents  tenure  \
0     7590-VHVEG  Female              0     Yes         No       1   
1     5575-GNVDE    Male              0      No         No      34   
2     3668-QPYBK    Male              0      No         No       2   
3     7795-CFOCW    Male              0      No         No      45   
4     9237-HQITU  Female              0      No         No       2   
...          ...     ...            ...     ...        ...     ...   
7038  6840-RESVB    Male              0     Yes        Yes      24   
7039  2234-XADUH  Female              0     Yes        Yes      72   
7040  4801-JZAZL  Female              0     Yes        Yes      11   
7041  8361-LTMKD    Male              1     Yes         No       4   
7042  3186-AJIEK    Male              0      No         No      66   

     PhoneService     MultipleLines InternetService OnlineSecurity  ...  \
0              No  No phone service             DSL 

In [4]:
telecom_cust.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [5]:
telecom_cust.TotalCharges = pd.to_numeric(telecom_cust.TotalCharges, errors='coerce')
telecom_cust.isnull().sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [6]:
telecom_cust.dropna(inplace = True)

In [7]:
df2 = telecom_cust.iloc[:,1:]

# 虛擬變數轉換

In [8]:
df2['Churn'].replace(to_replace='Yes', value=1, inplace=True)
df2['Churn'].replace(to_replace='No',  value=0, inplace=True)

In [9]:
df_dummies = pd.get_dummies(df2)
df_dummies.head()

SeniorCitizen  tenure  MonthlyCharges  TotalCharges  Churn  gender_Female  \
0              0       1           29.85         29.85      0              1   
1              0      34           56.95       1889.50      0              0   
2              0       2           53.85        108.15      1              0   
3              0      45           42.30       1840.75      0              0   
4              0       2           70.70        151.65      1              1   

   gender_Male  Partner_No  Partner_Yes  Dependents_No  ...  \
0            0           0            1              1  ...   
1            1           1            0              1  ...   
2            1           1            0              1  ...   
3            1           1            0              1  ...   
4            0           1            0              1  ...   

   StreamingMovies_Yes  Contract_Month-to-month  Contract_One year  \
0                    0                        1                  0   
1                    0                        0                  1   
2                    0                        1                  0   
3                    0                        0                  1   
4                    0                        1                  0   

   Contract_Two year  PaperlessBilling_No  PaperlessBilling_Yes  \
0                  0                    0                     1   
1                  0                    1                     0   
2                  0                    0                     1   
3                  0                    1                     0   
4                  0                    0                     1   

   PaymentMethod_Bank transfer (automatic)  \
0                                        0   
1                                        0   
2                                        0   
3                                        1   
4                                        0   

   PaymentMethod_Credit card (automatic)  PaymentMethod_Electronic check  \
0                                      0                               1   
1                                      0                               0   
2                                      0                               0   
3                                      0                               0   
4                                      0                               1   

   PaymentMethod_Mailed check  
0                           0  
1                           1  
2                           1  
3                           0  
4                           0  

[5 rows x 46 columns]

In [10]:
x= df_dummies.drop(columns=['Churn'])
y= df_dummies ['Churn']

# 資料切分為訓練集與測試集

In [11]:
x_train, x_test, y_train, y_test = train_test_split(x,y,stratify=y, test_size = 0.2, random_state = 0)

In [12]:
print(f"Training target statistics: {Counter(y_train)}")
print(f"Testing target statistics: {Counter(y_test)}")

Training target statistics: Counter({0: 4130, 1: 1495})
Testing target statistics: Counter({0: 1033, 1: 374})


In [13]:
print("Number transactions x_train dataset: ", x_train.shape)
print("Number transactions y_train dataset: ", y_train.shape)
print("Number transactions x_test dataset: ", x_test.shape)
print("Number transactions y_test dataset: ", y_test.shape)

Number transactions x_train dataset:  (5625, 45)
Number transactions y_train dataset:  (5625,)
Number transactions x_test dataset:  (1407, 45)
Number transactions y_test dataset:  (1407,)


# 模型訓練-LogisticRegression

In [14]:
from sklearn import linear_model

In [16]:
model=linear_model.LogisticRegression()
model.fit(x_train,y_train)

c:\users\angel\appdata\local\programs\python\python39\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [17]:
model.predict(x_test)

array([1, 0, 0, ..., 0, 0, 0], dtype=int64)

In [18]:
model.predict_proba(x_test)

array([[0.34469748, 0.65530252],
       [0.55867693, 0.44132307],
       [0.99064858, 0.00935142],
       ...,
       [0.67350866, 0.32649134],
       [0.99501526, 0.00498474],
       [0.81734196, 0.18265804]])

In [19]:
model.score(x_test,y_test)

0.8059701492537313

# 處理資料不平衡問題  方法一:隨機過取樣方法

In [20]:
!pip install imblearn 

You should consider upgrading via the 'c:\users\angel\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.


In [21]:
from collections import Counter

In [22]:
from imblearn.over_sampling import RandomOverSampler
over_sampler = RandomOverSampler(random_state=42)
x_res, y_res = over_sampler.fit_resample(x_train, y_train)
print(f"Training target statistics: {Counter(y_res)}")
print(f"Testing target statistics: {Counter(y_test)}")

Training target statistics: Counter({0: 4130, 1: 4130})
Testing target statistics: Counter({0: 1033, 1: 374})


In [24]:
model=linear_model.LogisticRegression()
model.fit(x_res,y_res)

c:\users\angel\appdata\local\programs\python\python39\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [25]:
model.predict(x_test)

array([1, 1, 0, ..., 1, 0, 0], dtype=int64)

In [26]:
model.predict_proba(x_test)

array([[0.16650652, 0.83349348],
       [0.30591805, 0.69408195],
       [0.96741912, 0.03258088],
       ...,
       [0.46343238, 0.53656762],
       [0.98098957, 0.01901043],
       [0.59903984, 0.40096016]])

In [27]:
model.score(x_test,y_test)

0.7633262260127932

# 處理資料不平衡問題  方法二:Smote

In [28]:
from imblearn.over_sampling import SMOTE
over_sampler = SMOTE(k_neighbors=2)
x_res, y_res = over_sampler.fit_resample(x_train, y_train)
print(f"Training target statistics: {Counter(y_res)}")
print(f"Testing target statistics: {Counter(y_test)}")

Training target statistics: Counter({0: 4130, 1: 4130})
Testing target statistics: Counter({0: 1033, 1: 374})


In [29]:
model=linear_model.LogisticRegression()
model.fit(x_res,y_res)

c:\users\angel\appdata\local\programs\python\python39\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [30]:
model.predict(x_test)

array([1, 1, 0, ..., 0, 0, 0], dtype=int64)

In [31]:
model.predict_proba(x_test)

array([[0.46777668, 0.53222332],
       [0.46313902, 0.53686098],
       [0.99437105, 0.00562895],
       ...,
       [0.54454463, 0.45545537],
       [0.99315187, 0.00684813],
       [0.9046477 , 0.0953523 ]])

In [32]:
model.score(x_test,y_test)

0.7853589196872779

# 處理資料不平衡問題 方法三:隨機欠取樣

In [33]:
from imblearn.under_sampling import RandomUnderSampler
UnderSampler = RandomUnderSampler(random_state=42)
x_res, y_res = UnderSampler.fit_resample(x_train, y_train)
print(f"Training target statistics: {Counter(y_res)}") 
print(f"Testing target statistics: {Counter(y_test)}")

Training target statistics: Counter({0: 1495, 1: 1495})
Testing target statistics: Counter({0: 1033, 1: 374})


In [34]:
from sklearn import linear_model
model=linear_model.LogisticRegression()
model.fit(x_res,y_res)

LogisticRegression()

In [35]:
model.predict(x_test)

array([1, 1, 0, ..., 1, 0, 0], dtype=int64)

In [36]:
model.predict_proba(x_test)

array([[0.14399785, 0.85600215],
       [0.30678523, 0.69321477],
       [0.96618591, 0.03381409],
       ...,
       [0.41501712, 0.58498288],
       [0.98381066, 0.01618934],
       [0.55744623, 0.44255377]])

In [37]:
model.score(x_test,y_test)

0.757640369580668